name: hornhuang_github_io
description: my website.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about_me Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about_me iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  provider: ^6.0.0
  # 轮播图
  flutter_swiper_null_safety: ^1.0.2
  # webview_flutter:
  webview_flutter: ^2.0.12
  flutter_macos_webview: ^0.0.5
  webview_windows: ^0.0.7
  # tab controller web
  easy_tab_controller: ^1.0.1
  # GetX is an extra-light and powerful solution for Flutter.
  get: ^4.1.3
  # 动画
  animations: ^2.0.0
  # dart:html 不支持 Android 所以要换成这个
  universal_html: ^1.2.1
  # Bmob 后端云
  data_plugin: ^0.0.18
  # flutter_bloc: mvvm
  flutter_bloc: ^7.2.0
  # dio: 网络请求
  dio: ^3.0.9

  camera:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  #  cupertino_icons: ^1.0.3 # Bomb 中添加了，这里无法再添加


#dependency_overrides:
#  flutter_web:
#    git:
#      url: https://github.com/flutter/website
#      path: packages/flutter_web
#  flutter_web_ui:
#    git:
#      url: https://github.com/flutter/website
#      path: packages/flutter_web_ui

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_ume: ^0.1.0  # null-safety 版本: ^0.2.1
  flutter_ume_kit_ui: ^0.1.0  # null-safety 版本: ^0.2.1
  flutter_ume_kit_device: ^0.1.0  # null-safety 版本: ^0.2.1
  flutter_ume_kit_perf: ^0.1.0  # null-safety 版本: ^0.2.1
  flutter_ume_kit_show_code: ^0.1.0  # null-safety 版本: ^0.2.1
  flutter_ume_kit_console: ^0.1.0  # null-safety 版本: ^0.2.1
#  flutter_ume_kit_dio: ^0.1.0  # 仅支持 null-safety 版本

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/Welfare/
    - assets/images/QuickLink/
    - assets/images/Index/
    - assets/files/html/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
